# Data Exploration

## Overview

Data exploration is the first analytical stage of the Movie Analytics SQL Project. The purpose of this stage is to develop a clear understanding of the database structure, the data contained within each table, and the relationships that connect the different entities.

The database contains information covering:

- Movies
- Actors
- Cast members
- Genres
- Keywords
- Languages
- Production companies
- Production countries
- Oscar awards

Before performing transformations or building analytical models, it is important to understand the characteristics and structure of these datasets.

## Objectives

The data exploration process will focus on:

- Identifying all tables available in the database.
- Understanding the structure and purpose of each table.
- Examining columns and data types.
- Identifying primary and foreign key relationships.
- Understanding the grain of each table.
- Measuring the number of records within each table.
- Examining unique and categorical values.
- Identifying potential missing and duplicate records.
- Understanding one-to-one, one-to-many, and many-to-many relationships.
- Identifying potential issues that could affect downstream analysis.

## Analytical Approach

The exploration will be performed using **SQL through SQLAlchemy**, with **Pandas** used to retrieve and inspect query results within the Jupyter Notebook.

The analysis will begin at the database level and progressively move toward table-level and column-level exploration.

Particular attention will be given to bridge tables because they represent **many-to-many relationships** and can introduce row multiplication when multiple tables are joined.

## Exploration Process

The exploration will cover the following areas:

1. Database and table inventory
2. Table structure and schema
3. Primary and foreign key relationships
4. Record counts
5. Column-level characteristics
6. Unique values and cardinality
7. Missing values
8. Duplicate records
9. Numerical and categorical fields
10. Relationships between tables

## Expected Outcome

At the end of the exploration stage, there should be a clear understanding of:

- What data is available.
- How the tables are structured.
- How the entities relate to one another.
- The grain of each table.
- Which fields can be used as keys.
- Potential data quality issues.
- Potential data modeling considerations.

The findings from this stage will provide the foundation for the subsequent stages of the project:

1. **Data Profiling**
2. **Data Quality Assessment**
3. **Data Modeling**
4. **Analytics Mart Development**
5. **Exploratory Data Analysis**
6. **Business Analysis and Insights**

> **Key Principle:** Before transforming or analyzing data, understand its structure, grain, relationships, and quality.

In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Importing the required libraries
import pandas as pd
import matplotlib.pyplot as plt
from  sqlalchemy import create_engine
from pathlib import Path

print("All libraries imported successfully!")

All libraries imported successfully!

In [5]:
# Creating a database engine
db_path = Path.home() / "Documents" / "Movie DB SQL Analytics" / "Database" / "TMDB-a-4006.db"

engine = create_engine(f"sqlite:///{db_path}")

In [6]:
# Testing the database connection
query = """
SELECT sqlite_version();
"""

pd.read_sql(query, engine)

  sqlite_version()
0           3.50.4

In [7]:
# Checking the tables in the database
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

tables = pd.read_sql(query, engine)

tables

                    name
0                 actors
1                  casts
2               genremap
3                 genres
4             keywordmap
5               keywords
6            languagemap
7              languages
8                 movies
9                 oscars
10   productioncompanies
11  productioncompanymap
12   productioncountries
13  productioncountrymap
14           sysdiagrams

In [8]:
# Number of tables in the database
len(tables)

15

In [9]:
# Counting the number of records in each table
record_counts = {}
for table in tables['name']:
    query = f"SELECT COUNT(*) AS count FROM {table};"
    count = pd.read_sql(query, engine).iloc[0]['count']
    record_counts[table] = count
    print(f"Number of records in {table}: {count}")

Number of records in actors: 54588
Number of records in casts: 106257
Number of records in genremap: 12160
Number of records in genres: 20
Number of records in keywordmap: 36194
Number of records in keywords: 9813
Number of records in languagemap: 6937
Number of records in languages: 87
Number of records in movies: 4803
Number of records in oscars: 9964
Number of records in productioncompanies: 5047
Number of records in productioncompanymap: 13677
Number of records in productioncountries: 88
Number of records in productioncountrymap: 6436
Number of records in sysdiagrams: 0

In [10]:
# Expolring actors table
pd.read_sql("""
PRAGMA table_info(actors);
""", engine)

   cid        name          type  notnull dflt_value  pk
0    0    actor_id       INTEGER        1        NaN   1
1    1  actor_name  varchar(100)        0       NULL   0
2    2      gender       INTEGER        0       NULL   0

In [ ]:
# Checking the first few records in the actors table
pd.read_sql("""
SELECT *
FROM actors;
""", engine)

       actor_id       actor_name  gender
0             1     George Lucas       2
1             2      Mark Hamill       2
2             3    Harrison Ford       2
3             4    Carrie Fisher       1
4             5    Peter Cushing       2
...         ...              ...     ...
54583   1893203       Sonia Rose       0
54584   1893204       Joey Nappo       0
54585   1893205  Michelle Brzenk       0
54586   1893206  Matthew Withers       0
54587   1893207    Skip P. Welch       0

[54588 rows x 3 columns]

In [13]:
# Expolring casts table
pd.read_sql("""
PRAGMA table_info(casts);
""", engine)

   cid        name          type  notnull dflt_value  pk
0    0    movie_id       INTEGER        1       None   1
1    1    actor_id       INTEGER        1       None   2
2    2  characters  varchar(500)        1       None   3

In [14]:
# Checking the first few records in the casts table
pd.read_sql("""
SELECT *
FROM casts;
""", engine)

        movie_id  actor_id            characters
0              5        62                   Leo
1              5       138          Chester Rush
2              5      2545  Long Hair Yuppy Scum
3              5      2555             Siegfried
4              5      3122               Jezebel
...          ...       ...                   ...
106252    433715   1500111                 Amber
106253    433715   1734573                    BB
106254    433715   1734574                 Sugar
106255    433715   1734575                  Drew
106256    459488   1354401              Narrator

[106257 rows x 3 columns]

In [15]:
# Expolring genremap table
pd.read_sql("""
PRAGMA table_info(genremap);
""", engine)

   cid      name     type  notnull dflt_value  pk
0    0  movie_id  INTEGER        1       None   1
1    1  genre_id  INTEGER        1       None   2

In [16]:
# Checking the first few records in the genremap table
pd.read_sql("""
SELECT *
FROM genremap;
""", engine)

       movie_id  genre_id
0            11        12
1            18        12
2            22        12
3            58        12
4            62        12
...         ...       ...
12155     78814     10770
12156    153397     10770
12157    158150     10770
12158    205321     10770
12159    231617     10770

[12160 rows x 2 columns]

In [17]:
# Expolring genres table
pd.read_sql("""
PRAGMA table_info(genres);
""", engine)

   cid        name         type  notnull dflt_value  pk
0    0    genre_id      INTEGER        1        NaN   1
1    1  genre_name  varchar(50)        0       NULL   0

In [18]:
# Checking the first few records in the genres table
pd.read_sql("""
SELECT *
FROM genres;
""", engine)

    genre_id       genre_name
0         12        Adventure
1         14          Fantasy
2         16        Animation
3         18            Drama
4         27           Horror
5         28           Action
6         35           Comedy
7         36          History
8         37          Western
9         53         Thriller
10        80            Crime
11        99      Documentary
12       878  Science Fiction
13      9648          Mystery
14     10402            Music
15     10749          Romance
16     10751           Family
17     10752              War
18     10769          Foreign
19     10770         TV Movie

In [ ]:
# Expolring keywordmap table
pd.read_sql("""
PRAGMA table_info(keywordmap);
""", engine)

   cid        name     type  notnull dflt_value  pk
0    0    movie_id  INTEGER        1       None   1
1    1  keyword_id  INTEGER        1       None   2

In [20]:
# Checking the first few records in the keywordmap table
pd.read_sql("""
SELECT *
FROM keywordmap;
""", engine)

       movie_id  keyword_id
0            16          30
1            65          30
2            77          30
3           197          30
4           207          30
...         ...         ...
36189     43884      238196
36190     43884      238197
36191     43884      238198
36192     43884      238206
36193     10317      238222

[36194 rows x 2 columns]

In [21]:
# Expolring keywords table
pd.read_sql("""
PRAGMA table_info(keywords);
""", engine)

   cid          name          type  notnull dflt_value  pk
0    0    keyword_id       INTEGER        1        NaN   1
1    1  keyword_name  varchar(500)        0       NULL   0

In [22]:
# Checking the first few records in the keywords table
pd.read_sql("""
SELECT *
FROM keywords;
""", engine)

      keyword_id       keyword_name
0             30         individual
1             65            holiday
2             74            germany
3             75         gunslinger
4             83   saving the world
...          ...                ...
9808      238196  the light brigade
9809      238197             horses
9810      238198    british lancers
9811      238206       society ball
9812      238222          year 2002

[9813 rows x 2 columns]

In [23]:
# Expolring languagemap table
pd.read_sql("""
PRAGMA table_info(languagemap);
""", engine)

   cid       name     type  notnull dflt_value  pk
0    0   movie_id  INTEGER        1       None   1
1    1  iso_639_1  char(2)        1       None   2

In [24]:
# Checking the first few records in the languagemap table
pd.read_sql("""
SELECT *
FROM languagemap;
""", engine)

      movie_id iso_639_1
0          868        af
1         1123        af
2         1372        af
3        17654        af
4        22600        af
...        ...       ...
6932    381902        zh
6933       868        zu
6934      1123        zu
6935     17654        zu
6936     29697        zu

[6937 rows x 2 columns]

In [25]:
# Checking the first few records in the languagemap table
pd.read_sql("""
SELECT *
FROM languagemap;
""", engine)

      movie_id iso_639_1
0          868        af
1         1123        af
2         1372        af
3        17654        af
4        22600        af
...        ...       ...
6932    381902        zh
6933       868        zu
6934      1123        zu
6935     17654        zu
6936     29697        zu

[6937 rows x 2 columns]

In [26]:
# Expolring languages table
pd.read_sql("""
PRAGMA table_info(languages);
""", engine)

   cid           name         type  notnull dflt_value  pk
0    0      iso_639_1      char(2)        1        NaN   1
1    1  language_name  varchar(50)        0       NULL   0

In [27]:
# Checking the first few records in the languages table
pd.read_sql("""
SELECT *
FROM languages;
""", engine)

   iso_639_1   language_name
0         af       Afrikaans
1         am             NaN
2         ar         ???????
3         bg  ????????? ????
4         bm      Bamanankan
..       ...             ...
82        xh             NaN
83        xx     No Language
84        yi             NaN
85        zh             ???
86        zu         isiZulu

[87 rows x 2 columns]

In [ ]:
# Expolring movies table
pd.read_sql("""
PRAGMA table_info(movies);
""", engine)

    cid               name           type  notnull dflt_value  pk
0     0           movie_id        INTEGER        1        NaN   1
1     1              title   varchar(500)        0       NULL   0
2     2       release_date    datetime(6)        0       NULL   0
3     3             budget        INTEGER        0       NULL   0
4     4           homepage   varchar(500)        0       NULL   0
5     5  original_language    varchar(50)        0       NULL   0
6     6     original_title   varchar(500)        0       NULL   0
7     7           overview  varchar(5000)        0       NULL   0
8     8         popularity         double        0       NULL   0
9     9            revenue         double        0       NULL   0
10   10            runtime         double        0       NULL   0
11   11     release_status    varchar(50)        0       NULL   0
12   12            tagline   varchar(500)        0       NULL   0
13   13       vote_average         double        0       NULL   0
14   14         vote_count        INTEGER        0       NULL   0

In [29]:
# Checking the first few records in the movies table
pd.read_sql("""
SELECT *
FROM movies;
""", engine)

,movie_id,title,release_date,budget,homepage,original_language,original_title,overview,popularity,revenue,runtime,release_status,tagline,vote_average,vote_count
0,5,Four Rooms,1995-12-09 00:00:00.000000,4000000,NaN,en,Four Rooms,It's Ted the Bellhop's first night on the job....,22.876230,4300000.0,98.0,Released,Twelve outrageous guests. Four scandalous requ...,6.5,530
1,11,Star Wars,1977-05-25 00:00:00.000000,11000000,http://www.starwars.com/films/star-wars-episod...,en,Star Wars,Princess Leia is captured and held hostage by ...,126.393695,775398007.0,121.0,Released,"A long time ago in a galaxy far, far away...",8.1,6624
2,12,Finding Nemo,2003-05-30 00:00:00.000000,94000000,http://movies.disney.com/finding-nemo,en,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",85.688789,940335536.0,100.0,Released,"There are 3.7 trillion fish in the ocean, they...",7.6,6122
3,13,Forrest Gump,1994-07-06 00:00:00.000000,55000000,NaN,en,Forrest Gump,A man with a low IQ has accomplished great thi...,138.133331,677945399.0,142.0,Released,"The world will never be the same, once you've ...",8.2,7927
4,14,American Beauty,1999-09-15 00:00:00.000000,15000000,http://www.dreamworks.com/ab/,en,American Beauty,"Lester Burnham, a depressed suburban father in...",80.878605,356296601.0,122.0,Released,Look closer.,7.9,3313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,426067,Midnight Cabaret,1990-01-01 00:00:00.000000,0,NaN,en,Midnight Cabaret,A Broadway producer puts on a play with a Devi...,0.001389,0.0,94.0,Released,The hot spot where Satan's waitin'.,0.0,0
4799,426469,Growing Up Smith,2017-02-03 00:00:00.000000,0,http://www.growingupsmithmovie.com,en,Growing Up Smith,"""In 1979, an Indian family moves to America wi...",0.710870,0.0,102.0,Released,ItÆs better to stand out than to fit in.,7.4,7
4800,433715,8 Days,2014-06-15 00:00:00.000000,0,NaN,en,8 Days,"After sneaking to a party with her friends, 16...",0.015295,0.0,90.0,Released,She never knew it could happen to her...,0.0,0
4801,447027,Running Forever,2015-10-27 00:00:00.000000,0,NaN,en,Running Forever,After being estranged since her mother's death...,0.028756,0.0,88.0,Released,NaN,0.0,0
4802,459488,"To Be Frank, Sinatra at 100",2015-12-12 00:00:00.000000,2,NaN,en,"To Be Frank, Sinatra at 100",NaN,0.050625,0.0,NaN,Released,NaN,0.0,0

In [30]:
# Expolring actors table
pd.read_sql("""
PRAGMA table_info(oscars);
""", engine)

   cid    name          type  notnull dflt_value  pk
0    0    year   varchar(10)        0       NULL   0
1    1   award  varchar(500)        0       NULL   0
2    2  winner   varchar(10)        0       NULL   0
3    3    name  varchar(500)        0       NULL   0
4    4    film  varchar(500)        0       NULL   0

In [31]:
# Checking the first few records in the oscars table
pd.read_sql("""
SELECT *
FROM casts;
""", engine)

        movie_id  actor_id            characters
0              5        62                   Leo
1              5       138          Chester Rush
2              5      2545  Long Hair Yuppy Scum
3              5      2555             Siegfried
4              5      3122               Jezebel
...          ...       ...                   ...
106252    433715   1500111                 Amber
106253    433715   1734573                    BB
106254    433715   1734574                 Sugar
106255    433715   1734575                  Drew
106256    459488   1354401              Narrator

[106257 rows x 3 columns]

In [32]:
# Checking the first few records in the oscars table
pd.read_sql("""
SELECT *
FROM oscars;
""", engine)

,year,award,winner,name,film
0,1928,Actor,NaN,Richard Barthelmess,The Noose
1,1928,Actor,1.0,Emil Jannings,The Last Command
2,1928,Actress,NaN,Louise Dresser,A Ship Comes In
3,1928,Actress,1.0,Janet Gaynor,7th Heaven
4,1928,Actress,NaN,Gloria Swanson,Sadie Thompson
...,...,...,...,...,...
9959,2015,Writing (Original Screenplay),1.0,Spotlight,Written by Josh Singer & Tom McCarthy
9960,2015,Writing (Original Screenplay),NaN,Straight Outta Compton,Screenplay by Jonathan Herman and Andrea Berlo...
9961,2015,Jean Hersholt Humanitarian Award,1.0,Debbie Reynolds,NaN
9962,2015,Honorary Award,1.0,Spike Lee,NaN
9963,2015,Honorary Award,1.0,Gena Rowlands,NaN

In [33]:
# Expolring actors table
pd.read_sql("""
PRAGMA table_info(productioncompanies);
""", engine)

   cid                     name          type  notnull dflt_value  pk
0    0    production_company_id       INTEGER        1        NaN   1
1    1  production_company_name  varchar(500)        0       NULL   0

In [34]:
# Checking the first few records in the productioncompanies table
pd.read_sql("""
SELECT *
FROM productioncompanies;
""", engine)

      production_company_id        production_company_name
0                         1                      Lucasfilm
1                         2           Walt Disney Pictures
2                         3        Pixar Animation Studios
3                         4             Paramount Pictures
4                         5              Columbia Pictures
...                     ...                            ...
5042                  94551           4Go West Productions
5043                  94552              Flatiron Pictures
5044                  94714        Vista Organisation, The
5045                  95018  MPH Entertainment Productions
5046                  95063                    Marcy Media

[5047 rows x 2 columns]

In [35]:
# Expolring actors table
pd.read_sql("""
PRAGMA table_info(productioncompanymap);
""", engine)

   cid                   name     type  notnull dflt_value  pk
0    0               movie_id  INTEGER        1       None   1
1    1  production_company_id  INTEGER        1       None   2

In [36]:
# Checking the first few records in the productioncompanymap table
pd.read_sql("""
SELECT *
FROM productioncompanymap;
""", engine)

       movie_id  production_company_id
0            11                      1
1            85                      1
2            87                      1
3            89                      1
4           217                      1
...         ...                    ...
13672     98549                  94551
13673     98549                  94552
13674     58048                  94714
13675      8346                  95018
13676    196867                  95063

[13677 rows x 2 columns]

In [37]:
# Expolring actors table
pd.read_sql("""
PRAGMA table_info(productioncountries);
""", engine)

   cid                     name         type  notnull dflt_value  pk
0    0               iso_3166_1      char(2)        1        NaN   1
1    1  production_country_name  varchar(50)        0       NULL   0

In [38]:
# Checking the first few records in the productioncountries table
pd.read_sql("""
SELECT *
FROM productioncountries;
""", engine)

   iso_3166_1   production_country_name
0          AE                    ??????
1          AF                   ???????
2          AO                    Angola
3          AR                 Argentina
4          AT               +ûsterreich
..        ...                       ...
83         TR                    ??????
84         TW                    ??????
85         UA                    ??????
86         US  United States of America
87         ZA              South Africa

[88 rows x 2 columns]

In [39]:
# Expolring actors table
pd.read_sql("""
PRAGMA table_info(productioncountrymap);
""", engine)

   cid        name     type  notnull dflt_value  pk
0    0    movie_id  INTEGER        0       NULL   0
1    1  iso_3166_1  char(2)        0       NULL   0

In [40]:
# Checking the first few records in the productioncountrymap table
pd.read_sql("""
SELECT *
FROM productioncountrymap;
""", engine)

      movie_id iso_3166_1
0            5         US
1           11         US
2           12         US
3           13         US
4           14         US
...        ...        ...
6431    407887         KR
6432    417859         US
6433    433715         US
6434    447027         US
6435    459488         GB

[6436 rows x 2 columns]