# Data Profiling

## Overview

Data profiling is the process of systematically examining the structure, completeness, consistency, and characteristics of the data before performing transformation or analysis.

The objective of this stage is to establish a clear understanding of the quality and distribution of the data across the movie database.

## Objectives

The data profiling process will focus on:

- Measuring the number of records in each table.
- Identifying the number of columns in each table.
- Examining column names and data types.
- Measuring the number of unique values.
- Identifying missing or null values.
- Detecting potential duplicate records.
- Examining numerical data distributions.
- Reviewing categorical value distributions.
- Identifying minimum and maximum values where applicable.
- Understanding the cardinality of key fields.
- Identifying potential data anomalies that require further investigation.

## Profiling Dimensions

The database will be profiled across the following dimensions:

### 1. Completeness

Determine whether required fields contain missing or null values and measure the percentage of incomplete records.

### 2. Uniqueness

Determine whether primary key fields contain duplicate values and assess the uniqueness of important business attributes.

### 3. Validity

Examine whether values conform to their expected data types, formats, and business meaning.

### 4. Consistency

Identify inconsistent values, naming conventions, or categorical representations across the database.

### 5. Distribution

Analyze the distribution of numerical and categorical fields to understand the characteristics of the underlying data.

### 6. Cardinality

Measure the number of distinct values within important fields to understand their uniqueness and relationship to the table grain.

## Analytical Approach

The profiling will be performed using **SQL through SQLAlchemy**, with **Pandas** used to retrieve and inspect profiling results within the Jupyter Notebook.

SQL queries will be used to calculate record counts, distinct values, null values, duplicates, and statistical measures. Pandas will then be used to organize and review the results.

## Expected Outcome

The profiling exercise will establish a baseline understanding of the database and highlight areas requiring further investigation during the **Data Quality Assessment** stage.

The results will help determine:

- Which tables require additional validation.
- Which columns contain missing values.
- Whether key fields are truly unique.
- Where potential anomalies exist.
- Which fields require transformation or standardization.
- How the data should be handled when developing the analytics marts.

> **Key Principle:** Data profiling establishes an evidence-based understanding of the data before any cleaning, transformation, or analytical modeling is performed.

In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Importing the required libraries
import pandas as pd
from  sqlalchemy import create_engine
from pathlib import Path

print("All libraries imported successfully!")

All libraries imported successfully!

In [5]:
# Creating a database engine
db_path = Path.home() / "Documents" / "Movie DB SQL Analytics" / "Database" / "TMDB-a-4006.db"

engine = create_engine(f"sqlite:///{db_path}")

print("Database Connection established successfully!")

Database Connection established successfully!

# Profiling the Actor Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [ ]:
# Row count of the actors table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM actors;
""", engine)

   Total
0  54588

In [12]:
# Distinct count of actors in the actors table
pd.read_sql("""
SELECT COUNT(DISTINCT actor_id)
FROM actors;
""", engine)

   COUNT(DISTINCT actor_id)
0                     54588

In [50]:
# Missing values in the actors table
pd.read_sql("""
SELECT COUNT(*)
FROM actors
WHERE actor_name IS NULL;
""", engine)

   COUNT(*)
0         0

In [59]:
# Duplicate actor_id values in the actors table
pd.read_sql("""
SELECT actor_id,
COUNT(*) AS Total
FROM actors
GROUP BY actor_id
HAVING COUNT(*) > 1;
""", engine)

Empty DataFrame
Columns: [actor_id, Total]
Index: []

# Profiling the Casts Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [ ]:
# Row count of the casts table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM casts;
""", engine)

    Total
0  106257

In [16]:
# Distinct count of casts in the casts table
pd.read_sql("""
SELECT COUNT(DISTINCT actor_id)
FROM casts;
""", engine)

   COUNT(DISTINCT actor_id)
0                     54588

In [54]:
# Missing values in the casts table
pd.read_sql("""
SELECT COUNT(*)
FROM casts
WHERE characters IS NULL;
""", engine)

   COUNT(*)
0         0

In [61]:
# Duplicate actor_id values in the casts table
pd.read_sql("""
SELECT characters,
COUNT(*) AS Total
FROM casts
GROUP BY characters
HAVING COUNT(*) > 1;
""", engine)

                                             characters  Total
0                                                          683
1                "ATM Child (segment ""Machine Kids"")"      2
2                             "Beatrice ""Tris"" Prior"      3
3     "Fake Wonder Woman (segment ""Super Hero Speed...      2
4     "Featured Woman (segment ""Don't"") (uncredited)"      2
...                                                 ...    ...
8292                               les habitu+¬s du bar      2
8293                                           producer      2
8294                                         stewardess      2
8295                                         un gar+ºon      2
8296                                              voice      2

[8297 rows x 2 columns]

# Profiling the Genremap Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [55]:
# Row count of the genremap table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM genremap;
""", engine)

   Total
0  12160

In [19]:
# Distinct count of actors in the genremap table
pd.read_sql("""
SELECT COUNT(DISTINCT genre_id)
FROM genremap;
""", engine)

   COUNT(DISTINCT genre_id)
0                        20

In [ ]:
# Missing values in the genremap table
pd.read_sql("""
SELECT COUNT(*)
FROM genremap
WHERE movie_id IS NULL;
""", engine)

       movie_id  genre_id
0            11        12
1            18        12
2            22        12
3            58        12
4            62        12
...         ...       ...
12155     78814     10770
12156    153397     10770
12157    158150     10770
12158    205321     10770
12159    231617     10770

[12160 rows x 2 columns]

In [63]:
# Duplicate genre_id values in the genremap table
pd.read_sql("""
SELECT genre_id,
COUNT(*) AS Total
FROM genremap
GROUP BY genre_id
HAVING COUNT(*) > 1;
""", engine)

    genre_id  Total
0         12    790
1         14    424
2         16    234
3         18   2297
4         27    519
5         28   1154
6         35   1722
7         36    197
8         37     82
9         53   1274
10        80    696
11        99    110
12       878    535
13      9648    348
14     10402    185
15     10749    894
16     10751    513
17     10752    144
18     10769     34
19     10770      8

# Profiling the Genres Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [20]:
# Row count of the genres table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM genres;
""", engine)

   Total
0     20

In [ ]:
# Distinct count of rows in the genres table
pd.read_sql("""
SELECT COUNT(DISTINCT genre_id)
FROM genres;
""", engine)

   COUNT(DISTINCT genre_id)
0                        20

In [ ]:
# Missing values in the genres table
pd.read_sql("""
SELECT COUNT(*)
FROM genres
WHERE genre_name IS NULL;
""", engine)

   COUNT(*)
0         0

In [70]:
# Duplicate genre_id values in the genres table
pd.read_sql("""
SELECT genre_name,
COUNT(*) AS Total
FROM genres
GROUP BY genre_name
HAVING COUNT(*) > 1;
""", engine)

Empty DataFrame
Columns: [genre_name, Total]
Index: []

# Profiling the Keywordmap Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [ ]:
# Row count of the keywordmap table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM keywordmap;
""", engine)

   Total
0  36194

In [ ]:
# Distinct count rows in the keywordmap table
pd.read_sql("""
SELECT COUNT(DISTINCT keyword_id)
FROM keywordmap;
""", engine)

   COUNT(DISTINCT keyword_id)
0                        9813

In [ ]:
# Missing values in the keywordmap table
pd.read_sql("""
SELECT COUNT(*)
FROM keywordmap
WHERE keyword_id IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate keyword_id values in the keywordmap table
pd.read_sql("""
SELECT movie_id,
COUNT(*) AS Total
FROM keywordmap
GROUP BY movie_id
HAVING COUNT(*) > 1;
""", engine)

      movie_id  Total
0            5     10
1           11     16
2           12     12
3           13     19
4           14     21
...        ...    ...
4098    402515      6
4099    407887      6
4100    417859      2
4101    433715      2
4102    459488      6

[4103 rows x 2 columns]

# Profiling the Keywords Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [ ]:
# Row count of the keywords table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM keywords;
""", engine)

   Total
0   9813

In [ ]:
# Distinct count of rows in the keywords table
pd.read_sql("""
SELECT COUNT(DISTINCT keyword_id)
FROM keywords;
""", engine)

   COUNT(DISTINCT keyword_id)
0                        9813

In [ ]:
# Missing values in the keywords table
pd.read_sql("""
SELECT COUNT(*)
FROM keywords
WHERE keyword_name IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate keyword_name values in the keywords table
pd.read_sql("""
SELECT keyword_name,
COUNT(*) AS Total
FROM keywords
GROUP BY keyword_name
HAVING COUNT(*) > 1;
""", engine)

  keyword_name  Total
0         ????      3

# Profiling the Languages Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [26]:
# Row count of the languages table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM languages;
""", engine)

   Total
0     87

In [30]:
# Distinct count of actors in the languages table
pd.read_sql("""
SELECT COUNT(DISTINCT ISO_639_1)
FROM languages;
""", engine)

   COUNT(DISTINCT ISO_639_1)
0                         87

In [ ]:
# Missing values in the languages table
pd.read_sql("""
SELECT COUNT(*)
FROM languages
--WHERE language_name IS NULL;
""", engine)

   COUNT(*)
0        87

In [ ]:
# Duplicate language_name values in the languages table
pd.read_sql("""
SELECT language_name,
COUNT(*) AS Total
FROM languages
GROUP BY language_name
HAVING COUNT(*) > 1;
""", engine)

  language_name  Total
0           NaN     26
1           ???      2
2          ????      2
3         ?????      4
4        ??????      4
5       ???????      3
6      ????????      2

# Profiling the Languagemap Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [31]:
# Row count of the languagemap table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM languagemap;
""", engine)

   Total
0   6937

In [33]:
# Distinct count of actors in the languagemap table
pd.read_sql("""
SELECT COUNT(DISTINCT ISO_639_1)
FROM languagemap;
""", engine)

   COUNT(DISTINCT ISO_639_1)
0                         87

In [ ]:
# Missing values in the languagemap table
pd.read_sql("""
SELECT COUNT(*)
FROM languagemap
WHERE movie_id IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate ISO_639_1 values in the languagemap table
pd.read_sql("""
SELECT movie_id,
COUNT(*) AS Total
FROM languagemap
GROUP BY movie_id
HAVING COUNT(*) > 1;
""", engine)

      movie_id  Total
0           18      3
1           24      3
2           25      4
3           28      4
4           58      4
...        ...    ...
1357    385383      2
1358    385636      2
1359    389425      2
1360    407887      2
1361    417859      2

[1362 rows x 2 columns]

# Profiling the Movies Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [34]:
# Row count of the movies table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM movies;
""", engine)

   Total
0   4803

In [35]:
# Distinct count of actors in the movies table
pd.read_sql("""
SELECT COUNT(DISTINCT movie_id)
FROM movies;
""", engine)

   COUNT(DISTINCT movie_id)
0                      4803

In [ ]:
# Missing values in the movies table
pd.read_sql("""
SELECT * --COUNT(*)
FROM movies
WHERE title IS NULL;
""", engine)

Empty DataFrame
Columns: [movie_id, title, release_date, budget, homepage, original_language, original_title, overview, popularity, revenue, runtime, release_status, tagline, vote_average, vote_count]
Index: []

In [88]:
# Duplicate title values in the movies table
pd.read_sql("""
SELECT title,
COUNT(*) AS Total
FROM movies
GROUP BY title
HAVING COUNT(*) > 1;
""", engine)

             title  Total
0           Batman      2
1  Out of the Blue      2
2         The Host      2

# Profiling the Oscars Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [38]:
# Row count of the oscars table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM oscars;
""", engine)

   Total
0   9964

In [ ]:
# Distinct count of actors in the oscars table
pd.read_sql("""
SELECT COUNT(DISTINCT award)
FROM oscars;
""", engine)

   COUNT(DISTINCT award)
0                    114

In [ ]:
# Missing values in the oscars table
pd.read_sql("""
SELECT COUNT(*)
FROM oscars
WHERE name IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate name values in the oscars table
pd.read_sql("""
SELECT name,
COUNT(*) AS Total
FROM oscars
GROUP BY name
HAVING COUNT(*) > 1;
""", engine)

                               name  Total
0                     12 Angry Men       3
1                 12 Years a Slave       6
2                        127 Hours       4
3                              1941      3
4     20,000 Leagues under the Sea       3
...                             ...    ...
1592                 Young Winston       3
1593                             Z       5
1594                         Zelig       2
1595              Zero Dark Thirty       4
1596               Zorba the Greek       5

[1597 rows x 2 columns]

# Profiling the Productioncompanies Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [41]:
# Row count of the productioncompanies table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM ProductionCompanies;
""", engine)

   Total
0   5047

In [43]:
# Distinct count of actors in the productioncompanies table
pd.read_sql("""
SELECT COUNT(DISTINCT production_company_id)
FROM productioncompanies;
""", engine)

   COUNT(DISTINCT production_company_id)
0                                   5047

In [ ]:
# Missing values in the productioncompanies table
pd.read_sql("""
SELECT COUNT(*)
FROM productioncompanies
WHERE production_company_name IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate production_company_name values in the productioncompanies table
pd.read_sql("""
SELECT production_company_name,
COUNT(*) AS Total
FROM productioncompanies
GROUP BY production_company_name
HAVING COUNT(*) > 1;
""", engine)

                   production_company_name  Total
0                     3 Arts Entertainment      2
1                        Anonymous Content      2
2                  Automatik Entertainment      2
3                   Blue Tulip Productions      2
4                          Bluegrass Films      2
5                       Blueprint Pictures      2
6   British Broadcasting Corporation (BBC)      2
7               British Screen Productions      2
8                                    CinT+      2
9                  Don Carmody Productions      2
10        Donner/Shuler-Donner Productions      2
11              Esparza / Katz Productions      2
12                             Film i VSst      2
13        Filmstiftung Nordrhein-Westfalen      2
14                         France 2 CinTma      3
15                               HSX Films      2
16                    Ignite Entertainment      2
17                      Magnolia Mae Films      2
18            Majestic Films International      2
19              Merchant Ivory Productions      2
20             Michael De Luca Productions      2
21             Nu Image Entertainment GmbH      2
22                          Number 9 Films      2
23                    Plan B Entertainment      2
24                Sandcastle 5 Productions      2
25                       Showtime Networks      2
26                           Stage 6 Films      2
27  Union GTnTrale CinTmatographique (UGC)      2
28                       VIP 2 Medienfonds      2

# Profiling the Productioncompanymap Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [44]:
# Row count of the productioncompanymap table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM productioncompanymap;
""", engine)

   Total
0  13677

In [45]:
# Distinct count of actors in the productioncompanymap table
pd.read_sql("""
SELECT COUNT(DISTINCT production_company_id)
FROM productioncompanymap;
""", engine)

   COUNT(DISTINCT production_company_id)
0                                   5047

In [ ]:
# Missing values in the productioncompanymap table
pd.read_sql("""
SELECT COUNT(*)
FROM productioncompanymap
WHERE movie_id IS NULL;
""", engine)

   COUNT(*)
0         0

In [98]:
# Duplicate movie_id values in the productioncompanymap table
pd.read_sql("""
SELECT movie_id,
COUNT(*) AS Total
FROM productioncompanymap
GROUP BY movie_id
HAVING COUNT(*) > 1;
""", engine)

      movie_id  Total
0            5      2
1           11      2
2           14      2
3           16     26
4           18      2
...        ...    ...
3381    380733      2
3382    385636      2
3383    385736      3
3384    389425      2
3385    394047      2

[3386 rows x 2 columns]

# Profiling the Productioncountries Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [46]:
# Row count of the productioncountries table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM productioncountries;
""", engine)

   Total
0     88

In [47]:
# Distinct count of actors in the productioncountries table
pd.read_sql("""
SELECT COUNT(DISTINCT ISO_3166_1)
FROM productioncountries;
""", engine)

   COUNT(DISTINCT ISO_3166_1)
0                          88

In [ ]:
# Missing values in the productioncountries table
pd.read_sql("""
SELECT COUNT(*)
FROM productioncountries
WHERE production_country_name IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate production_company_name values in the productioncompanies table
pd.read_sql("""
SELECT production_company_name,
COUNT(*) AS Total
FROM productioncompanies
GROUP BY production_company_name
HAVING COUNT(*) > 1;
""", engine)

                   production_company_name  Total
0                     3 Arts Entertainment      2
1                        Anonymous Content      2
2                  Automatik Entertainment      2
3                   Blue Tulip Productions      2
4                          Bluegrass Films      2
5                       Blueprint Pictures      2
6   British Broadcasting Corporation (BBC)      2
7               British Screen Productions      2
8                                    CinT+      2
9                  Don Carmody Productions      2
10        Donner/Shuler-Donner Productions      2
11              Esparza / Katz Productions      2
12                             Film i VSst      2
13        Filmstiftung Nordrhein-Westfalen      2
14                         France 2 CinTma      3
15                               HSX Films      2
16                    Ignite Entertainment      2
17                      Magnolia Mae Films      2
18            Majestic Films International      2
19              Merchant Ivory Productions      2
20             Michael De Luca Productions      2
21             Nu Image Entertainment GmbH      2
22                          Number 9 Films      2
23                    Plan B Entertainment      2
24                Sandcastle 5 Productions      2
25                       Showtime Networks      2
26                           Stage 6 Films      2
27  Union GTnTrale CinTmatographique (UGC)      2
28                       VIP 2 Medienfonds      2

# Profiling the Productioncountrymap Table
### - Row Count
### - Distinct count
### - Missing Value
### - Duplicate Values

In [48]:
# Row count of the productioncountrymap table
pd.read_sql("""
SELECT COUNT(*) AS Total
FROM productioncountrymap;
""", engine)

   Total
0   6436

In [49]:
# Distinct count of actors in the productioncountrymap table
pd.read_sql("""
SELECT COUNT(DISTINCT ISO_3166_1)
FROM productioncountrymap;
""", engine)

   COUNT(DISTINCT ISO_3166_1)
0                          88

In [ ]:
# Missing values in the productioncountrymap table
pd.read_sql("""
SELECT COUNT(*)
FROM productioncountrymap
WHERE movie_id IS NULL;
""", engine)

   COUNT(*)
0         0

In [ ]:
# Duplicate movie_id values in the productioncountrymap table
pd.read_sql("""
SELECT movie_id,
COUNT(*) AS Total
FROM productioncountrymap
GROUP BY movie_id
HAVING COUNT(*) > 1;
""", engine)

      movie_id  Total
0           16     12
1           20      2
2           25      2
3           58      4
4           59      3
...        ...    ...
1241    357834      2
1242    358451      2
1243    360339      3
1244    361475      2
1245    381902      2

[1246 rows x 2 columns]